#!/bin/bash
# =============================================================================
# ds4-deepseek-v4-flash-mtp-start.sh — 2-node ds4 (DeepSeek V4 Flash) launch
#
# Generated by the ds4-deepseek-v4-flash-mtp bootstrap playbook (2026-09-02T00:39:23Z).
# One script for both nodes; choose the role via env:
#   DS4_ROLE=head    -> node 1 (halo0): ds4-server coordinator, layers 0:21,
#                       MTP drafter, OpenAI API on port 8000
#   DS4_ROLE=worker  -> node 2 (halo1): ds4-server worker, layers 22:output,
#                       joins the coordinator on port 8081
#
# Start the HEAD first, then the WORKER. The pipeline channel rides the
# Thunderbolt link (tb*, ~40 Gbps) when up — see setup-thunderbolt-net.yml;
# falls back to the 2.5Gbe NIC.
#
# Requires the ds4_cluster container from the ds4-deepseek-v4-flash-mtp
# track bootstrap (image docker.io/kyuz0/strix-halo-ds4-toolbox:multi-node-rocm-7.2.4). Model weights are downloaded
# into ~/ds4 on the host (mounted at /root/ds4 in the container) on first
# run — the ~153 GB main GGUF on BOTH nodes, the ~3.6 GB MTP drafter on
# the head only.
#
# The playbook never launches servers: this is where the cluster comes up.
# =============================================================================
set -euo pipefail

# --- role (env required) ---
DS4_ROLE="${DS4_ROLE:?set DS4_ROLE=head|worker}"

# --- baked config (override via env) ---
DS4_HF_REPO="${DS4_HF_REPO:-antirez/deepseek-v4-gguf}"
DS4_MODEL_FILE="${DS4_MODEL_FILE:-DeepSeek-V4-Flash-Q4KExperts-F16HC-F16Compressor-F16Indexer-Q8Attn-Q8Shared-Q8Out-chat-v2-imatrix.gguf}"
DS4_MTP_FILE="${DS4_MTP_FILE:-DeepSeek-V4-Flash-MTP-Q4K-Q8_0-F32.gguf}"
DS4_CTX="${DS4_CTX:-262144}"
DS4_MTP_DRAFT="${DS4_MTP_DRAFT:-1}"
DS4_LAYERS_HEAD="${DS4_LAYERS_HEAD:-0:21}"
DS4_LAYERS_WORKER="${DS4_LAYERS_WORKER:-22:output}"
DS4_PP_PORT="${DS4_PP_PORT:-8081}"
DS4_API_PORT="${DS4_API_PORT:-8000}"
DS4_HEAD_IP="${DS4_HEAD_IP:-10.125.0.1}"
DS4_WORKER_IP="${DS4_WORKER_IP:-10.125.0.2}"
CONTAINER="ds4_cluster"
SERVER="/usr/local/bin/ds4-server"

ensure_container() {
  if [ "$(sudo podman ps --filter name=${CONTAINER} --format '{{.Names}}')" = "${CONTAINER}" ]; then
    return 0
  fi
  echo "Container ${CONTAINER} is not running — starting it ..." >&2
  sudo podman start "${CONTAINER}"
}

# Download a model file into /root/ds4 inside the container if missing.
ensure_file() {
  local f="$1"
  if sudo podman exec "${CONTAINER}" test -f "/root/ds4/${f}"; then
    return 0
  fi
  echo "Downloading ${f} from ${DS4_HF_REPO} (first run only) ..." >&2
  sudo podman exec "${CONTAINER}" \
    HF_XET_HIGH_PERFORMANCE=1 hf download "${DS4_HF_REPO}" "${f}" --local-dir /root/ds4
}

case "${DS4_ROLE}" in
  head)
    [ -n "${DS4_HEAD_IP}" ] || { echo "DS4_HEAD_IP not set — re-run the track with the inventory group or -e ds4_head_ip=..." >&2; exit 1; }
    ensure_container
    ensure_file "${DS4_MODEL_FILE}"
    ensure_file "${DS4_MTP_FILE}"

    echo "Starting ds4 coordinator on ${DS4_HEAD_IP} (layers ${DS4_LAYERS_HEAD}, MTP on, pipeline port ${DS4_PP_PORT}) ..."
    # First-run model load is slow (~153 GB mmap + weights); watch with:
    #   sudo podman logs -f ${CONTAINER}
    sudo podman exec -d "${CONTAINER}" "${SERVER}" \
      -m "/root/ds4/${DS4_MODEL_FILE}" \
      --ctx "${DS4_CTX}" \
      --mtp "/root/ds4/${DS4_MTP_FILE}" \
      --mtp-draft "${DS4_MTP_DRAFT}" \
      --role coordinator --layers "${DS4_LAYERS_HEAD}" \
      --listen "${DS4_HEAD_IP}" "${DS4_PP_PORT}"

    echo "CLUSTER HEAD READY (when warm) — OpenAI endpoint: http://${DS4_HEAD_IP}:${DS4_API_PORT}/v1"
    echo "Health poll:  curl -s http://${DS4_HEAD_IP}:${DS4_API_PORT}/v1/models"
    echo "Logs:         sudo podman logs -f ${CONTAINER}"
    echo "NOTE: the worker joins lazily — start it on node 2 with DS4_ROLE=worker."
    ;;
  worker)
    [ -n "${DS4_HEAD_IP}" ] || { echo "DS4_HEAD_IP not set — re-run the track with the inventory group or -e ds4_head_ip=..." >&2; exit 1; }
    ensure_container
    ensure_file "${DS4_MODEL_FILE}"

    echo "Joining coordinator ${DS4_HEAD_IP}:${DS4_PP_PORT} as worker (layers ${DS4_LAYERS_WORKER}) ..."
    sudo podman exec -d "${CONTAINER}" "${SERVER}" \
      -m "/root/ds4/${DS4_MODEL_FILE}" \
      --ctx "${DS4_CTX}" \
      --role worker --layers "${DS4_LAYERS_WORKER}" \
      --coordinator "${DS4_HEAD_IP}" "${DS4_PP_PORT}"

    echo "WORKER READY — watch the coordinator on the head: sudo podman logs -f ${CONTAINER}"
    echo "NOTE: the worker uses the SAME model/ctx as the head; it serves nothing directly."
    ;;
  *)
    echo "Unknown DS4_ROLE '${DS4_ROLE}'" >&2; exit 1 ;;
esac