#!/bin/bash
# =============================================================================
# ds4-start.sh — DeepSeek V4 Flash (ds4) launch script
#
# Generated by the ds4 bootstrap playbook (2026-08-24T00:00:00Z).
# One script for both nodes; choose the role via env:
#   DS4_ROLE=single      -> standalone IQ2_XXS server (single node)
#   DS4_ROLE=coordinator -> multi-node coordinator (layers 0:21, listens)
#   DS4_ROLE=worker      -> multi-node worker (layers 22:output, connects)
#
# MTP speculative decoding is DISABLED by default (stability). Enable with
# DS4_USE_MTP=1 if you want it (negatively affects stability, small speed gain).
#
# Run inside the ds4 distrobox:  distrobox enter <toolbox> -- bash /path/to/ds4-start.sh
# (the toolbox name is baked below; override with DS4_TOOLBOX if needed)
# =============================================================================
set -euo pipefail

# --- role (env required) ---
DS4_ROLE="${DS4_ROLE:?set DS4_ROLE=single|coordinator|worker}"

# --- baked config (override via env) ---
DS4_MODEL="${DS4_MODEL:-DeepSeek-V4-Flash-Q4KExperts-F16HC-F16Compressor-F16Indexer-Q8Attn-Q8Shared-Q8Out-chat-v2-imatrix.gguf}"
DS4_MTP="${DS4_MTP:-DeepSeek-V4-Flash-MTP-Q4K-Q8_0-F32.gguf}"
DS4_USE_MTP="${DS4_USE_MTP:-0}"                       # disabled by default
DS4_CTX="${DS4_CTX:-262144}"
DS4_PORT="${DS4_PORT:-8000}"
DS4_COORD_IP="${DS4_COORD_IP:-192.168.100.1}"
DS4_COORD_PORT="${DS4_COORD_PORT:-8081}"
DS4_MODELS_DIR="${DS4_MODELS_DIR:-$HOME/ds4}"
DS4_TOOLBOX="${DS4_TOOLBOX:-docker.io/kyuz0/strix-halo-ds4-toolbox:multi-node-rocm-7.14}"
# Single-node toolbox (use for DS4_ROLE=single): docker.io/kyuz0/strix-halo-ds4-toolbox:rocm-7.14

# --- optional MTP (speculative decoding) args ---
MTP_ARGS=""
[ "$DS4_USE_MTP" = "1" ] && MTP_ARGS="--mtp $DS4_MODELS_DIR/$DS4_MTP"
COORD_MTP_ARGS=""
[ "$DS4_USE_MTP" = "1" ] && COORD_MTP_ARGS="--mtp $DS4_MODELS_DIR/$DS4_MTP --mtp-draft 1"

case "$DS4_ROLE" in
  single)
    echo "Starting ds4 SINGLE-NODE server on 0.0.0.0:$DS4_PORT ..."
    distrobox enter "$DS4_TOOLBOX" -- \
      ds4-server -m "$DS4_MODELS_DIR/$DS4_MODEL" --ctx "$DS4_CTX" \
        --host 0.0.0.0 --port "$DS4_PORT" $MTP_ARGS
    echo "Endpoint: http://localhost:$DS4_PORT/v1"
    ;;
  coordinator)
    [ -n "$DS4_COORD_IP" ] || { echo "DS4_COORD_IP not set" >&2; exit 1; }
    echo "Starting ds4 COORDINATOR (layers 0:21) on $DS4_COORD_IP:$DS4_COORD_PORT ..."
    distrobox enter "$DS4_TOOLBOX" -- \
      ds4-server -m "$DS4_MODELS_DIR/$DS4_MODEL" --ctx "$DS4_CTX" \
        --role coordinator --layers 0:21 \
        --listen "$DS4_COORD_IP" "$DS4_COORD_PORT" $COORD_MTP_ARGS
    ;;
  worker)
    [ -n "$DS4_COORD_IP" ] || { echo "DS4_COORD_IP not set" >&2; exit 1; }
    echo "Starting ds4 WORKER (layers 22:output) -> $DS4_COORD_IP:$DS4_COORD_PORT ..."
    distrobox enter "$DS4_TOOLBOX" -- \
      ds4-server -m "$DS4_MODELS_DIR/$DS4_MODEL" --ctx "$DS4_CTX" \
        --role worker --layers 22:output \
        --coordinator "$DS4_COORD_IP" "$DS4_COORD_PORT" $MTP_ARGS
    ;;
  *)
    echo "Unknown DS4_ROLE '$DS4_ROLE'" >&2; exit 1 ;;
esac