#!/bin/bash
# =============================================================================
# gemma-start.sh — Gemma 4 26B-A4B (8-bit UD-Q8_K_XL) via latest llama.cpp
#
# Generated by the llama bootstrap playbook (2026-08-25T22:27:08Z).
#
# Optimized for Strix Halo (Ryzen AI Max / gfx1151) per the Frame.work LLM
# bench thread (community.frame.work/t/72521, user lhl):
#   • Vulkan (Mesa RADV) wins token-gen + MoE prompt on Strix Halo; ROCm
#     7.x official had a pp regression. We build llama.cpp with Vulkan only.
#   • MoE: 2^n batching (batch=256) + flash-attn on.
#   • --no-mmap loads all weights into the unified 128GB shared pool.
#   • tg is memory-bandwidth bound (~215 GB/s): 8-bit UD-Q8_K_XL keeps
#     active ~4B params ≈ 4 GB/token ≈ 40-50 tok/s; ~2x BF16.
#
# Env overrides: GEMMA_BIN/LIB/MODEL/CTX/PORT/HOST/DEVICE/BATCH/UBATCH/FA/MMAP/THREADS
# =============================================================================
set -euo pipefail

GEMMA_MODEL="${GEMMA_MODEL:-/home/jdella/.local/share/llama-models/gemma-4-26B-A4B-it-UD-Q8_K_XL.gguf}"
GEMMA_BIN="${GEMMA_BIN:-/home/jdella/llama-cpp/bin/llama-server}"
GEMMA_CTX="${GEMMA_CTX:-131072}"
GEMMA_PORT="${GEMMA_PORT:-8080}"
GEMMA_HOST="${GEMMA_HOST:-127.0.0.1}"
GEMMA_DEVICE="${GEMMA_DEVICE:-Vulkan0}"
GEMMA_BATCH="${GEMMA_BATCH:-256}"
GEMMA_UBATCH="${GEMMA_UBATCH:-512}"
GEMMA_FA="${GEMMA_FA:-1}"
GEMMA_MMAP="${GEMMA_MMAP:-0}"
GEMMA_THREADS="${GEMMA_THREADS:-16}"

# --- llama.cpp shared libs (libllama-server-impl.so, libllama.so, libggml-vulkan.so)
#     install into $GEMMA_BIN/../lib; the binary has no rpath, so add it to the loader path ---
GEMMA_LIB="${GEMMA_LIB:-$(dirname "$GEMMA_BIN")/../lib}"
[ -d "$GEMMA_LIB" ] && export LD_LIBRARY_PATH="${GEMMA_LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

# --- Vulkan (Mesa RADV) runtime env for Strix Halo ---
export AMD_VULKAN_ICD=RADV
export RADV_PERFTEST="gpl,sam,nggc"
# discover all ICDs (RADV + AMD pro) so Vulkan0 is picked; RADV is fastest here
for _icd in /usr/share/vulkan/icd.d/*.json; do
  VK_ICD_FILENAMES="${VK_ICD_FILENAMES:+${VK_ICD_FILENAMES}:}${_icd}"
done
export VK_ICD_FILENAMES

# --- sanity ---
[ -x "$GEMMA_BIN" ] || { echo "llama-server not found: $GEMMA_BIN (run bootstrap)" >&2; exit 1; }
[ -f "$GEMMA_MODEL" ] || { echo "model not found: $GEMMA_MODEL" >&2; exit 1; }

# --- flag assembly (env-overridable) ---
FA_ARGS=()
[ "$GEMMA_FA" = "1" ] && FA_ARGS=(--flash-attn on)
MMAP_ARGS=(--no-mmap)
[ "$GEMMA_MMAP" = "1" ] && MMAP_ARGS=()

echo "Gemma 4 26B-A4B (UD-Q8_K_XL) on $GEMMA_DEVICE, ctx=$GEMMA_CTX, b=$GEMMA_BATCH, ub=$GEMMA_UBATCH"
echo "Endpoint: http://$GEMMA_HOST:$GEMMA_PORT/v1   alias: gemma-4-26b-a4b"

exec "$GEMMA_BIN" \
  --model "$GEMMA_MODEL" \
  --alias gemma-4-26b-a4b \
  --device "$GEMMA_DEVICE" \
  --n-gpu-layers 999 \
  --ctx-size "$GEMMA_CTX" \
  --batch-size "$GEMMA_BATCH" \
  --ubatch-size "$GEMMA_UBATCH" \
  --threads "$GEMMA_THREADS" \
  --cont-batching \
  --host "$GEMMA_HOST" --port "$GEMMA_PORT" \
  "${FA_ARGS[@]}" "${MMAP_ARGS[@]}" \
  "$@"
