#!/bin/bash
# =============================================================================
# gemma-e4b-start.sh — Gemma 4 E4B (Q4_K_S, ~4.8 GB) via latest llama.cpp
#
# Generated by the llama bootstrap playbook (2026-08-25T22:57:49Z).
#
# Gemma 4 E4B — 4.5B effective / 8B total (PLE embeddings), 42 layers,
#   512-token sliding window, 128K native context. Text+image+audio.
#
# Optimized for Strix Halo (Ryzen AI Max / gfx1151):
#   • Vulkan (Mesa RADV) — fastest tg + dense pp on Strix Halo.
#   • Dense model: no MoE, batch=512 / ubatch=1024 for max token throughput.
#   • --no-mmap loads all weights into the unified 128GB shared pool.
#   • ~4.5B effective params ≈ 4.5 GB/token — very fast tg (expect ~150-200+ tok/s).
#   • Reasoning: include <|think|> in system prompt to enable thinking mode.
#     Output: <|channel>thought\n[reasoning]<channel|>[final answer].
#
# Env overrides: GEMMA_E4B_BIN/LIB/MODEL/CTX/PORT/HOST/DEVICE/BATCH/UBATCH/FA/MMAP/THREADS
# =============================================================================
set -euo pipefail

GEMMA_E4B_MODEL="${GEMMA_E4B_MODEL:-/home/jdella/.local/share/llama-models/gemma-4-E4B-it-Q4_K_S.gguf}"
GEMMA_E4B_BIN="${GEMMA_E4B_BIN:-/home/jdella/llama-cpp/bin/llama-server}"
GEMMA_E4B_CTX="${GEMMA_E4B_CTX:-131072}"
GEMMA_E4B_PORT="${GEMMA_E4B_PORT:-8083}"
GEMMA_E4B_HOST="${GEMMA_E4B_HOST:-127.0.0.1}"
GEMMA_E4B_DEVICE="${GEMMA_E4B_DEVICE:-Vulkan0}"
GEMMA_E4B_BATCH="${GEMMA_E4B_BATCH:-512}"
GEMMA_E4B_UBATCH="${GEMMA_E4B_UBATCH:-1024}"
GEMMA_E4B_FA="${GEMMA_E4B_FA:-1}"
GEMMA_E4B_MMAP="${GEMMA_E4B_MMAP:-0}"
GEMMA_E4B_THREADS="${GEMMA_E4B_THREADS:-32}"

# --- llama.cpp shared libs (libllama-server-impl.so, libllama.so, libggml-vulkan.so)
#     install into $GEMMA_E4B_BIN/../lib; the binary has no rpath, so add it to the loader path ---
GEMMA_E4B_LIB="${GEMMA_E4B_LIB:-$(dirname "$GEMMA_E4B_BIN")/../lib}"
[ -d "$GEMMA_E4B_LIB" ] && export LD_LIBRARY_PATH="${GEMMA_E4B_LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

# --- Vulkan (Mesa RADV) runtime env for Strix Halo ---
export AMD_VULKAN_ICD=RADV
export RADV_PERFTEST="gpl,sam,nggc"
for _icd in /usr/share/vulkan/icd.d/*.json; do
  VK_ICD_FILENAMES="${VK_ICD_FILENAMES:+${VK_ICD_FILENAMES}:}${_icd}"
done
export VK_ICD_FILENAMES

# --- sanity ---
[ -x "$GEMMA_E4B_BIN" ] || { echo "llama-server not found: $GEMMA_E4B_BIN (run bootstrap)" >&2; exit 1; }
[ -f "$GEMMA_E4B_MODEL" ] || { echo "model not found: $GEMMA_E4B_MODEL" >&2; exit 1; }

# --- flag assembly (env-overridable) ---
FA_ARGS=()
[ "$GEMMA_E4B_FA" = "1" ] && FA_ARGS=(--flash-attn on)
MMAP_ARGS=(--no-mmap)
[ "$GEMMA_E4B_MMAP" = "1" ] && MMAP_ARGS=()

echo "Gemma 4 E4B (Q4_K_S, ~4.8 GB, 4.5B eff/8B total) on $GEMMA_E4B_DEVICE, ctx=$GEMMA_E4B_CTX, b=$GEMMA_E4B_BATCH, ub=$GEMMA_E4B_UBATCH"
echo "Endpoint: http://$GEMMA_E4B_HOST:$GEMMA_E4B_PORT/v1   alias: gemma-4-e4b"
echo "Reasoning: add <|think|> to system prompt to enable. Sampling: temp=1.0, top_p=0.95, top_k=64."

exec "$GEMMA_E4B_BIN" \
  --model "$GEMMA_E4B_MODEL" \
  --alias gemma-4-e4b \
  --device "$GEMMA_E4B_DEVICE" \
  --n-gpu-layers 999 \
  --ctx-size "$GEMMA_E4B_CTX" \
  --batch-size "$GEMMA_E4B_BATCH" \
  --ubatch-size "$GEMMA_E4B_UBATCH" \
  --threads "$GEMMA_E4B_THREADS" \
  --cont-batching \
  --host "$GEMMA_E4B_HOST" --port "$GEMMA_E4B_PORT" \
  --temp 1.0 --top-p 0.95 --top-k 64 \
  "${FA_ARGS[@]}" "${MMAP_ARGS[@]}" \
  "$@"
