#!/bin/bash
# =============================================================================
# laguna-start.sh — Laguna S 2.1 (Chadrock ROCmFP4 StrixKVSpine V4) via
#                    Ciru ROCmFPX Runtime V3
#
# Generated by the llama bootstrap playbook (2026-08-26T03:28:17Z).
#
# AMD-optimized ROCmFP4 quant at 4.453 BPW for Strix Halo (gfx1151).
# 118B total / ~8B active MoE, 60.945 GiB, 131K validated context.
# Runtime V3: Vulkan stability fixes (FA dispatch split, node cap 10),
# JSON grammar fixes, checkpoint safety for hybrid/SWA contexts.
#
# This does NOT run in stock upstream llama.cpp — requires Ciru ROCmFPX.
#
# Env overrides: LAGUNA_BIN/LIB/MODEL/CTX/PORT/HOST
# =============================================================================
set -euo pipefail

LAGUNA_MODEL="${LAGUNA_MODEL:-/home/jdella/.local/share/llama-models/laguna-s-2.1-ROCmFP4-StrixKVSpine-v4.gguf}"
LAGUNA_BIN="${LAGUNA_BIN:-/home/jdella/rocml-fpx/build-laguna-strix-vulkan/bin/llama-server}"
LAGUNA_CTX="${LAGUNA_CTX:-131072}"
LAGUNA_PORT="${LAGUNA_PORT:-8082}"
LAGUNA_HOST="${LAGUNA_HOST:-127.0.0.1}"
LAGUNA_THREADS="${LAGUNA_THREADS:-16}"
LAGUNA_BATCH="${LAGUNA_BATCH:-2048}"
LAGUNA_UBATCH="${LAGUNA_UBATCH:-512}"

# --- ROCmFPX binary dir ---
LAGUNA_BIN_DIR="${LAGUNA_BIN_DIR:-$(dirname "$LAGUNA_BIN")}"
[ -d "$LAGUNA_BIN_DIR" ] && export PATH="${LAGUNA_BIN_DIR}${PATH:+:$PATH}"

# --- Vulkan (Mesa RADV) runtime env for Strix Halo ---
export AMD_VULKAN_ICD=RADV
export RADV_PERFTEST="gpl,sam,nggc"
for _icd in /usr/share/vulkan/icd.d/*.json; do
  VK_ICD_FILENAMES="${VK_ICD_FILENAMES:+${VK_ICD_FILENAMES}:}${_icd}"
done
export VK_ICD_FILENAMES

# --- ROCmFPX V2/V3 Vulkan stability env vars ---
export GGML_VK_MAX_NODES_PER_SUBMIT=10
export GGML_VK_FA_MAX_WORKGROUPS_X_PER_DISPATCH=4

# --- Context checkpoints disabled (validated profile) ---
# The hybrid/SWA checkpoint path has not completed multi-turn qualification.
# Normal KV cache and prompt cache remain fully functional.
CTX_CHECKPOINTS="${CTX_CHECKPOINTS:-0}"

# --- Sanity ---
[ -x "$LAGUNA_BIN" ] || { echo "ROCmFPX llama-server not found: $LAGUNA_BIN (run bootstrap)" >&2; exit 1; }
[ -f "$LAGUNA_MODEL" ] || { echo "model not found: $LAGUNA_MODEL" >&2; exit 1; }

# --- Sampler JSON (V3 validated profile) ---
SAMPLER_FILE=$(mktemp /tmp/laguna-sampler-XXXXXX.json)
cat > "$SAMPLER_FILE" << 'SAMPLER'
{
  "temperature": 1.0,
  "top_p": 1.0,
  "top_k": 20,
  "min_p": 0.0,
  "repeat_penalty": 1.0,
  "seed": 42
}
SAMPLER
trap "rm -f '$SAMPLER_FILE'" EXIT

# --- 256K experimental lane ---
STABILITY_MODE="${STABILITY_MODE:-}"
if [ -n "$STABILITY_MODE" ] && [ "$STABILITY_MODE" = "performance" ]; then
  echo "WARNING: 256K experimental lane — not yet fully validated (multi-turn, cache-replay)."
fi

echo "Laguna S 2.1 ROCmFP4 StrixKVSpine V4 (60.95 GB, 4.453 BPW) on Vulkan0"
echo "ctx=$LAGUNA_CTX, b=$LAGUNA_BATCH, ub=$LAGUNA_UBATCH, threads=$LAGUNA_THREADS"
echo "Endpoint: http://$LAGUNA_HOST:$LAGUNA_PORT/v1   alias: laguna-s21-rocmfp4"

exec "$LAGUNA_BIN" \
  --model "$LAGUNA_MODEL" \
  --alias laguna-s21-rocmfp4 \
  --device "Vulkan0" \
  --n-gpu-layers 999 \
  --ctx-size "$LAGUNA_CTX" \
  --batch-size "$LAGUNA_BATCH" \
  --ubatch-size "$LAGUNA_UBATCH" \
  --threads "$LAGUNA_THREADS" \
  --no-mmap \
  --flash-attn on \
  --cont-batching \
  --ctx-checkpoints "$CTX_CHECKPOINTS" \
  --no-context-visual \
  --host "$LAGUNA_HOST" --port "$LAGUNA_PORT" \
  --sampling-strategy file \
  --strategy-file "$SAMPLER_FILE" \
  "$@"
