#!/bin/bash
# =============================================================================
# ornith15-start.sh — Ornith-1.5-35B-A3B (Q8_0, ~37.8 GB) via latest llama.cpp
#
# Generated by the llama bootstrap playbook (2026-08-26T11:40:48Z).
#
# Ornith-1.5-35B-A3B — 35B total / ~3B active (MoE), 256K native context
#   Vision-language model with agentic coding strengths.
#   Q8_0 quant at 37.80 GB.
#
# Optimized for Strix Halo (gfx1151) — ROCm/HIP backend:
#   • ROCm 4.7× faster prompt processing, 65% less energy than Vulkan.
#   • MoE: batch=64, ubatch=128 (reduced for KV cache fit on 128 GB UMA).
#   • --no-mmap loads weights into the unified 128GB shared pool.
#   • --cache-ram 0 prevents host/GPU memory competition on 128GB UMA.
#   • ~3B active params ≈ 3 GB/token ≈ 65-70 tok/s at ~215 GB/s.
#   • Reasoning: Qwen-style <think>...</think></think> format.
#   • Supports: reasoning_content (chain-of-thought), tool calls (XML format),
#     vision (image/video input via <|vision_start|><|image_pad|><|vision_end|>).
#
# Env overrides: ORNITH15_BIN/LIB/MODEL/CTX/PORT/HOST/DEVICE/BATCH/UBATCH/FA/MMAP/THREADS
# =============================================================================
set -euo pipefail

ORNITH15_MODEL="${ORNITH15_MODEL:-/home/jdella/.local/share/llama-models/Ornith-1.5-35B-Q8_0.gguf}"
ORNITH15_BIN="${ORNITH15_BIN:-/home/jdella/llama-cpp/bin/llama-server}"
ORNITH15_CTX="${ORNITH15_CTX:-131072}"
ORNITH15_PORT="${ORNITH15_PORT:-8085}"
ORNITH15_HOST="${ORNITH15_HOST:-127.0.0.1}"
ORNITH15_DEVICE="${ORNITH15_DEVICE:-ROCm0}"
ORNITH15_BATCH="${ORNITH15_BATCH:-64}"
ORNITH15_UBATCH="${ORNITH15_UBATCH:-128}"
ORNITH15_FA="${ORNITH15_FA:-1}"
ORNITH15_MMAP="${ORNITH15_MMAP:-0}"
ORNITH15_THREADS="${ORNITH15_THREADS:-16}"

# --- llama.cpp shared libs (libllama-server-impl.so, libllama.so, libggml-hip.so)
#     install into $ORNITH15_BIN/../lib; the binary has no rpath, so add it to the loader path ---
ORNITH15_LIB="${ORNITH15_LIB:-$(dirname "$ORNITH15_BIN")/../lib}"
[ -d "$ORNITH15_LIB" ] && export LD_LIBRARY_PATH="${ORNITH15_LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

# --- ROCm/HIP runtime env for Strix Halo ---
export HSA_ENABLE_SDMA=1
export HSA_FORCE_FINE_GRAIN_PCIE=1

# --- sanity ---
[ -x "$ORNITH15_BIN" ] || { echo "llama-server not found: $ORNITH15_BIN (run bootstrap)" >&2; exit 1; }
[ -f "$ORNITH15_MODEL" ] || { echo "model not found: $ORNITH15_MODEL" >&2; exit 1; }

# --- flag assembly (env-overridable) ---
FA_ARGS=()
[ "$ORNITH15_FA" = "1" ] && FA_ARGS=(--flash-attn on)
MMAP_ARGS=(--no-mmap)
[ "$ORNITH15_MMAP" = "1" ] && MMAP_ARGS=()

echo "Ornith-1.5-35B-A3B (Q8_0, ~37.8 GB, 35B total/~3B active MoE) on $ORNITH15_DEVICE, ctx=$ORNITH15_CTX, b=$ORNITH15_BATCH, ub=$ORNITH15_UBATCH"
echo "Endpoint: http://$ORNITH15_HOST:$ORNITH15_PORT/v1   alias: ornith-1.5-35b-a3b"
echo "Reasoning: Qwen-style <think>...</think></think> format. Sampling: temp=0.6, top_p=0.95, top_k=20."
echo "Vision: supports image/video input. Tools: XML <tool_call> format."

exec "$ORNITH15_BIN" \
  --model "$ORNITH15_MODEL" \
  --alias ornith-1.5-35b-a3b \
  --device "$ORNITH15_DEVICE" \
  --n-gpu-layers 999 \
  --ctx-size "$ORNITH15_CTX" \
  --batch-size "$ORNITH15_BATCH" \
  --ubatch-size "$ORNITH15_UBATCH" \
  --threads "$ORNITH15_THREADS" \
  --cont-batching \
  --cache-ram 0 \
  --host "$ORNITH15_HOST" --port "$ORNITH15_PORT" \
  --temp 0.6 --top-p 0.95 --top-k 20 \
  "${FA_ARGS[@]}" "${MMAP_ARGS[@]}" \
  "$@"
