#!/bin/bash
# =============================================================================
# step35flash-start.sh — Step 3.5 Flash (IQ4_XS, ~100.5 GB) via latest llama.cpp
#
# Generated by the llama bootstrap playbook (2026-08-26T09:48:33Z).
#
# Step 3.5 Flash — 26B total / 11B active (MoE), 256K native context
#   (3:1 Sliding Window Attention ratio). IQ4_XS quant at 4.38 BPW.
#
# Optimized for Strix Halo (gfx1151) per StepFun's validated Vulkan profile:
#   • Vulkan (Mesa RADV) wins tg + MoE pp; built Vulkan-only.
#   • MoE: batch=2048, ubatch=2048 (validated for 16384 ctx; use ubatch=1024
#     for 256K context).
#   • --no-mmap loads weights into the unified 128GB shared pool.
#   • ~11B active params ≈ 11 GB/token ≈ 30-48 tok/s at ~215 GB/s.
#   • Reasoning: Step-style `<|begin_of_thought|>` / `<|end_of_thought|>` format.
#
# Env overrides: STEP35FLASH_BIN/LIB/MODEL/CTX/PORT/HOST/DEVICE/BATCH/UBATCH/FA/MMAP/THREADS
# =============================================================================
set -euo pipefail

STEP35FLASH_MODEL="${STEP35FLASH_MODEL:-/home/jdella/.local/share/llama-models/Step-3.5-Flash-IQ4_XS-00001-of-00003.gguf}"
STEP35FLASH_BIN="${STEP35FLASH_BIN:-/home/jdella/llama-cpp/bin/llama-server}"
STEP35FLASH_CTX="${STEP35FLASH_CTX:-131072}"
STEP35FLASH_PORT="${STEP35FLASH_PORT:-8084}"
STEP35FLASH_HOST="${STEP35FLASH_HOST:-127.0.0.1}"
STEP35FLASH_DEVICE="${STEP35FLASH_DEVICE:-Vulkan0}"
STEP35FLASH_BATCH="${STEP35FLASH_BATCH:-2048}"
STEP35FLASH_UBATCH="${STEP35FLASH_UBATCH:-2048}"
STEP35FLASH_FA="${STEP35FLASH_FA:-1}"
STEP35FLASH_MMAP="${STEP35FLASH_MMAP:-0}"
STEP35FLASH_THREADS="${STEP35FLASH_THREADS:-32}"

# --- llama.cpp shared libs (libllama-server-impl.so, libllama.so, libggml-vulkan.so)
#     install into $STEP35FLASH_BIN/../lib; the binary has no rpath, so add it to the loader path ---
STEP35FLASH_LIB="${STEP35FLASH_LIB:-$(dirname "$STEP35FLASH_BIN")/../lib}"
[ -d "$STEP35FLASH_LIB" ] && export LD_LIBRARY_PATH="${STEP35FLASH_LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

# --- Vulkan (Mesa RADV) runtime env for Strix Halo ---
export AMD_VULKAN_ICD=RADV
export RADV_PERFTEST="gpl,sam,nggc"
for _icd in /usr/share/vulkan/icd.d/*.json; do
  VK_ICD_FILENAMES="${VK_ICD_FILENAMES:+${VK_ICD_FILENAMES}:}${_icd}"
done
export VK_ICD_FILENAMES

# --- sanity ---
[ -x "$STEP35FLASH_BIN" ] || { echo "llama-server not found: $STEP35FLASH_BIN (run bootstrap)" >&2; exit 1; }
[ -f "$STEP35FLASH_MODEL" ] || { echo "model not found: $STEP35FLASH_MODEL" >&2; exit 1; }

# --- flag assembly (env-overridable) ---
FA_ARGS=()
[ "$STEP35FLASH_FA" = "1" ] && FA_ARGS=(--flash-attn on)
MMAP_ARGS=(--no-mmap)
[ "$STEP35FLASH_MMAP" = "1" ] && MMAP_ARGS=()

echo "Step 3.5 Flash (IQ4_XS, ~100.5 GB, 11B active/26B total MoE) on $STEP35FLASH_DEVICE, ctx=$STEP35FLASH_CTX, b=$STEP35FLASH_BATCH, ub=$STEP35FLASH_UBATCH"
echo "Endpoint: http://$STEP35FLASH_HOST:$STEP35FLASH_PORT/v1   alias: step-3.5-flash"
echo "Reasoning: Step-style <|begin_of_thought|> / <|end_of_thought|> format. Sampling: temp=1.0, top_p=0.95, top_k=20."

exec "$STEP35FLASH_BIN" \
  --model "$STEP35FLASH_MODEL" \
  --alias step-3.5-flash \
  --device "$STEP35FLASH_DEVICE" \
  --n-gpu-layers 999 \
  --ctx-size "$STEP35FLASH_CTX" \
  --batch-size "$STEP35FLASH_BATCH" \
  --ubatch-size "$STEP35FLASH_UBATCH" \
  --threads "$STEP35FLASH_THREADS" \
  --cont-batching \
  --host "$STEP35FLASH_HOST" --port "$STEP35FLASH_PORT" \
  --temp 1.0 --top-p 0.95 --top-k 20 \
  "${FA_ARGS[@]}" "${MMAP_ARGS[@]}" \
  "$@"
